INSERT INTO company (full_name, ticker) VALUES
    ('3M Co.', 'MMM'), 
    ('American Express Co.', 'AXP'),
    ('Apple, Inc.', 'AAPL'),
    ('The Boeing Co.', 'BA'),
    ('Caterpillar, Inc.', 'CAT'),
    ('Chevron Corp.', 'CVX'),
    ('Cisco Systems, Inc.', 'CSCO'),
    ('The Coca-Cola Co.', 'KO'),
    ('Dow, Inc.', 'DOW'),
    ('Exxon Mobil Corp.', 'XOM'),
    ('The Goldman Sachs Group, Inc.', 'GS'),
    ('The Home Depot, Inc.', 'HD'),
    ('International Business Machines Corp.', 'IBM'),
    ('Intel Corp.', 'INTC'),
    ('Johnson & Johnson', 'JNJ'),
    ('JPMorgan Chase & Co.', 'JPM'),
    ('McDonald`s Corp.', 'MCD'),
    ('Merck & Co., Inc.', 'MRK'),
    ('Microsoft Corp.', 'MSFT'),
    ('NIKE, Inc.', 'NKE'),
    ('Pfizer Inc.', 'PFE'),
    ('Procter & Gamble Co.', 'PG'),
    ('The Travelers Cos., Inc.', 'TRV'),
    ('UnitedHealth Group, Inc.', 'UNH'),
    ('United Technologies Corp.', 'UTX'),
    ('Verizon Communications, Inc.', 'VZ'),
    ('Visa, Inc.', 'V'),
    ('Walmart, Inc.', 'WMT'),
    ('Walgreens Boots Alliance, Inc.', 'WBA'),
    ('The Walt Disney Co.', 'DIS');